services:
  - type: static
    name: crownstroke-frontend
    staticSite:
      source: ./dist
      publicPath: /
    buildCommand: npm install && npm run build:client
    envVars:
      - key: VITE_API_URL
        value: https://ratings-cartoons-david-cameras.trycloudflare.com
    autoDeploy: true

databases:
  - name: crownstroke-db
    type: postgresql